# Generated by Django 3.2.15 on 2024-01-21 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=50, unique=True)),
                ('correo', models.CharField(max_length=50, unique=True)),
                ('reset_token', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Accesos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acceso_predict', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'accesos',
            },
        ),
        migrations.CreateModel(
            name='Marca_Venado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Marcas_Venado',
            },
        ),
        migrations.CreateModel(
            name='Producto_venado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('cont_net', models.CharField(max_length=50)),
                ('linea_producto', models.CharField(max_length=50)),
                ('marca_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.marca_venado')),
            ],
            options={
                'db_table': 'Productos_venado',
            },
        ),
        migrations.CreateModel(
            name='Produccion_venado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_produccion_mensual', models.CharField(max_length=15)),
                ('cantidad_produccion', models.IntegerField()),
                ('marca_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.marca_venado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.producto_venado')),
            ],
            options={
                'db_table': 'produccion_venado',
            },
        ),
        migrations.CreateModel(
            name='Distribuciones_venado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_distribucion_mensual', models.CharField(max_length=15)),
                ('canal_horizontal', models.IntegerField()),
                ('canal_tradicional', models.IntegerField()),
                ('canal_moderno', models.IntegerField()),
                ('total_cantidad_distribucion', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.producto_venado')),
            ],
            options={
                'db_table': 'Distribucion_venado',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaPredicciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomproducto', models.CharField(max_length=255)),
                ('Fechaseleccionada', models.DateField()),
                ('fechaprediccion', models.DateField()),
                ('horaprediccion', models.TimeField()),
                ('cantprediccion', models.IntegerField()),
                ('modelo', models.CharField(max_length=255)),
                ('arL1', models.FloatField()),
                ('maL1', models.FloatField()),
                ('arSL2', models.FloatField()),
                ('sigma2', models.FloatField()),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditoria_predicciones',
            },
        ),
        migrations.AddField(
            model_name='usuarios',
            name='acceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.accesos'),
        ),
    ]
